# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: AI超元域的博客
# email: win4r@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  AI超元域频道的技术博客。分享AI技术、AI项目、开源大模型、大模型微调、RAG、AIAgent、提示词工程等AI前沿内容。 
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.aivi.fyi/" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: AISuperDomain
# github_username:  win4r
# youtube_username: AISuperDomain
# bilibili_username: AISuperDomain

locale: "zh-CN"

# Build settings
# theme: minimal-mistakes-jekyll

remote_theme: "mmistakes/minimal-mistakes@4.26.2"
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-feed


minimal_mistakes_skin: "air"

# plugins:
#   - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


defaults:
  # _posts
  - scope:
      path: ""
      type: pages
    values:
      author_profile: true
      sidebar: 
        nav: "docs"

      


author:
  name: "AI超元域"
  avatar: "/assets/images/bio-photo.jpg"
  bio: " **AI超元域up主**" # Note: Markdown is allowed
  location: "新加坡"
  links:
    - label: "X"
      icon: "fab fa-fw fa-x-twitter"
      url: "https://x.com/AISuperDomain"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/win4r/AISuperDomain"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/@AIsuperdomain"
    - label: "哔哩哔哩"
      icon: "fab fa-fw fa-bilibili"  
      # 或使用通用图标
      # icon: "fas fa-fw fa-play-circle"
      url: "https://b23.tv/S7VBv0M"
    # - label: "WeChat"
    #   icon: "fab fa-fw fa-weixin"
    #   url: "#wechat-id"  # 可以链接到关于页面或具体说明页面






keep_files: [images, downloads, assets,_data]


permalink: /:categories/:title/

favicon: /assets/images/favicon.ico
